sudo: required   # forces legacy build infrastructure
group: travis_lts   # forces most stable build images

language: cpp

matrix:
  fast_finish: true
  include:
  - os: linux
    dist: trusty
    env: BUILDTYPE=Debug
  - os: linux
    dist: trusty
    env: BUILDTYPE=Release
  - os: osx
    osx_image: xcode7.3
    env: BUILDTYPE=Debug
  - os: osx
    osx_image: xcode7.3
    env: BUILDTYPE=Release

cache: ccache

install: bash ./.travis/travis-dependencies.sh

script: bash ./.travis/travis-compile.sh

after_success: "echo $TRAVIS_TAG $BUILDTYPE"

# Builds for pull requests skip the deployment step altogether
deploy:
# Deploy configuration for "beta" releases
  - provider: releases
    api_key:
      secure: "8hffeD345YXAbFscQmdgjcGN5AmHV+JYfW650QEuQa/f4/lQFsVRtEqUA1O3FQ0OuRxdpCfJubZBdFVH8SbZ93GLC5zXJbkWQNq+xCX1fU="
    skip_cleanup: true
    name: "Cockatrice $TRAVIS_TAG"
    body: "Beta release of Cockatrice"
    file_glob: true
    file: "build/Cockatrice-*"
    overwrite: true
    draft: false
    prerelease: true
    on:
      condition: $TRAVIS_TAG =~ (\d|[1-9]\d)(\.(\d|[1-9]\d)){2}-beta(|\.([2-9]|[1-9]\d))$
      tags: true
      
# Deploy configuration for "stable" releases
  - provider: releases
    api_key:
      secure: "öihu8FscQmdgjcGN5AmHV+JYfW650QEuQa/f4/lQFsVRtEqUA1O3FQ0OuRxdpCfJubZBdFVH8SbZ93GLC5zXJbkWQNq+xCX1fU="
    skip_cleanup: true
    file_glob: true
    file: "build/Cockatrice-*"
    overwrite: true
    draft: false
    prerelease: false
    on:
      tags: true
      condition: $BUILDTYPE = Release && $TRAVIS_TAG =~ (\\d|[1-9]\\d)(\.(\\d|[1-9]\\d)){2}$


notifications:
  webhooks:
    urls:
#    - https://webhooks.gitter.im/e/d94969c3b01b22cbdcb7
    on_success: change
    on_failure: change
    on_start: never
 
 
# official validator for ".travis.yml" config file: https://yaml.travis-ci.org
# travis config documentation: https://docs.travis-ci.com/user/customizing-the-build
