sudo: required   # forces legacy build infrastructure
group: travis_lts   # forces most stable build images

language: cpp

matrix:
  fast_finish: true
  include:
  - os: linux
    dist: trusty
    env: BUILDTYPE=Debug DIST=trusty
  - os: linux
    dist: trusty
    env: BUILDTYPE=Release DIST=trusty
  - os: osx
    osx_image: xcode7.3
    env: BUILDTYPE=Debug
    cache:
      ccache: true
      timeout: 360 # 6min timeout for cache uploading instead default 3
      directories:
        - $HOME/Library/Caches/Homebrew   # cache Homebrew ressources
  - os: osx
    osx_image: xcode7.3
    env: BUILDTYPE=Release
    cache:
      ccache: true
      timeout: 360 # 6min timeout for cache uploading instead default 3
      directories:
        - $HOME/Library/Caches/Homebrew   # cache Homebrew ressources

cache: ccache

install: bash ./.travis/travis-dependencies.sh

script: bash ./.travis/travis-compile.sh

after_success: "echo $TRAVIS_TAG $BUILDTYPE"

before_deploy: "echo $TRAVIS_TAG"

# Builds for pull requests skip the deployment step altogether
deploy:
# Deploy config for "beta" releases
  - provider: releases
    api_key:
      secure: "mLMF41q7xgOR1sj34cd"
    skip_cleanup: true
    name: "Cockatrice $TRAVIS_TAG"
    body: "Beta release of Cockatrice"
    file_glob: true
    file: "build/Cockatrice-*"
    overwrite: true
    draft: false
    prerelease: true
    on:
      tags: true
      condition: "$BUILDTYPE = Release && $TRAVIS_TAG =~ [1-9][0-9]?(.([0-9]|[1-9][0-9])){2}-beta[1-9]$"
      
# Deploy config for "stable" releases
  - provider: releases
    api_key:
      secure: "mLMF41q7xgOR1sjczsilEy7HQa4ffd"
    skip_cleanup: true
    file_glob: true
    file: "build/Cockatrice-*"
    overwrite: true
    draft: false
    prerelease: false
    on:
      tags: true
      condition: "$BUILDTYPE = Release && $TRAVIS_TAG =~ [1-9][0-9]?(.([0-9]|[1-9][0-9])){2}$"


notifications:
  webhooks:
    urls:
#    - https://webhooks.gitter.im/e/d94969c3b01b22cbdcb7
    on_success: change
    on_failure: change
    on_start: never
 
 
# official validator for ".travis.yml" config file: https://yaml.travis-ci.org
# travis config documentation: https://docs.travis-ci.com/user/customizing-the-build
