sudo: false   # forces container-based build infrastructure for linux

language: cpp

cache: ccache


matrix:
  fast_finish: true
  include:
  - os: linux
    dist: trusty
    group: stable
    env: BUILDTYPE=Debug
    if: 
  - os: linux
    dist: trusty
    group: stable
    env: BUILDTYPE=Release
    if: (branch = master AND NOT type = pull_request) OR tag IS present
  - os: osx
    osx_image: xcode8
    env: BUILDTYPE=Debug
    if: 
  - os: osx
    osx_image: xcode8
    env: BUILDTYPE=Release
    if: (branch = master AND NOT type = pull_request) OR tag IS present

# install dependencies for container-based linux environment
addons:
  apt:
    packages:
    - bc
    - cmake  
    - libprotobuf-dev
    - protobuf-compiler
    - qt5-default
    - qttools5-dev
    - qttools5-dev-tools
    - qtmultimedia5-dev
    - libqt5multimedia5-plugins
    - libqt5svg5-dev
    - libqt5sql5-mysql


before_install: bash ./.travis/travis-dependencies.sh

script: bash ./.travis/travis-compile.sh

after_success: "echo $TRAVIS_TAG $BUILDTYPE"


# Builds for pull requests skip the deployment step altogether
deploy:
# Deploy configuration for "beta" releases
  - provider: releases
    api_key:
      secure: "8hffeD345YXAbFscQmdgjcGN5AmHV+JYfW650QEuQa/f4/lQFsVRtEqUA1O3FQ0OuRxdpCfJubZBdFVH8SbZ93GLC5zXJbkWQNq+xCX1fU="
    skip_cleanup: true
    name: "Cockatrice $TRAVIS_TAG"
    body: "Beta release of Cockatrice"
    file_glob: true
    file: "build/Cockatrice-*"
    overwrite: true
    draft: false
    prerelease: true
    on:
      condition: $BUILDTYPE = Release && $TRAVIS_TAG =~ ([0-9]|[1-9][0-9])(\.([0-9]|[1-9][0-9])){2}-beta(\.([2-9]|[1-9][0-9]))?$
      tags: true
      
# Deploy configuration for "stable" releases
  - provider: releases
    api_key:
      secure: "öihu8FscQmdgjcGN5AmHV+JYfW650QEuQa/f4/lQFsVRtEqUA1O3FQ0OuRxdpCfJubZBdFVH8SbZ93GLC5zXJbkWQNq+xCX1fU="
    skip_cleanup: true
    file_glob: true
    file: "build/Cockatrice-*"
    overwrite: true
    draft: false
    prerelease: false
    on:
      tags: true
      condition: $BUILDTYPE = Release && $TRAVIS_TAG =~ ([0-9]|[1-9][0-9])(\.([0-9]|[1-9][0-9])){2}$ 


notifications:
  webhooks:
    urls:
#    - https://webhooks.gitter.im/e/d94969c3b01b22cbdcb7
    on_success: change
    on_failure: change
    on_start: never
 
 
# official validator for ".travis.yml" config file: https://yaml.travis-ci.org
# travis config documentation: https://docs.travis-ci.com/user/customizing-the-build
