# info: https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/
# syntax: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms

name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug]
#assignees:
#  - octocat
body:

  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: dropdown
    id: os
    attributes:
      label: What operating system are you seeing the problem on?
      multiple: true
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Cockatrice Version
      description: Please provide the version you are running. (Where to find it? [test link](https://www.google.com))
      placeholder: e.g. "2.8.0 (2021-01-26)"
    validations:
      required: true

  - type: textarea
    id: system-details
    attributes:
      label: System Details
      description: We need to understand what version and environment you are running in.
      placeholder: |
          Copy your system informatino here! (Alternative)
          
          Example:
          "Client Version: 2.8.1-custom(ff6f562) (2021-06-29)
          Client Operating System: Windows 10 (10.0)
          Build Architecture: 64-bit
          Qt Version: 5.12.9
          System Locale: de_DE
          Install Mode: Standard"
    validations:
      required: false
 
  - type: textarea
    id: issue-details
    attributes:
      label: Issue Details
      description: We need to understand what problem you are running into.
      placeholder: Describe your problem as detailed as possible and provide screenshots where applicable.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: We need to understand what problem you are running into.
      value: |
          1. Do A
          2. Then check B
          3. C happens...
    validations:
      required: true

#possible to use this for the detailed system info input from debug log as well? no placeholder possible it seems like?
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: false

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
